BEGIN;

ALTER TABLE users ADD COLUMN IF NOT EXISTS employee_type TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS clinic_specialty TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS source_other TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS created_by BIGINT REFERENCES users(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS practice_manager_name TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS practice_manager_phone TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS practice_manager_email TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS practice_manager_linkedin TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS practice_manager_position TEXT;
ALTER TABLE leads ALTER COLUMN status SET DEFAULT 'New';

CREATE TABLE IF NOT EXISTS lead_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  assigned_to BIGINT NOT NULL REFERENCES users(id),
  assigned_by BIGINT NOT NULL REFERENCES users(id),
  assigned_at TIMESTAMPTZ DEFAULT NOW(),
  active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS call_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  employee_id BIGINT NOT NULL REFERENCES users(id),
  call_status TEXT NOT NULL CHECK (call_status IN ('Called', 'No Answer')),
  called_at TIMESTAMPTZ DEFAULT NOW(),
  notes TEXT
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE followups ADD COLUMN IF NOT EXISTS interest_status TEXT;
ALTER TABLE followups ADD COLUMN IF NOT EXISTS contract_type TEXT;
ALTER TABLE followups ADD COLUMN IF NOT EXISTS not_interested_reason TEXT;
ALTER TABLE followups ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;

UPDATE leads SET lead_id = 'LD-' || LPAD(id::TEXT, 6, '0')
WHERE lead_id IS NULL OR lead_id !~ '^LD-[0-9]{6}$';
UPDATE leads SET status = 'New' WHERE status IN ('Not contract', 'New Lead');

CREATE UNIQUE INDEX IF NOT EXISTS idx_leads_lead_id_unique ON leads(lead_id);
CREATE INDEX IF NOT EXISTS idx_leads_created_by ON leads(created_by);
CREATE INDEX IF NOT EXISTS idx_lead_assignments_active ON lead_assignments(assigned_to, active);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, is_read, created_at DESC);

ALTER TABLE lead_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE call_attempts DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
GRANT ALL ON lead_assignments, call_attempts, notifications TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

COMMIT;
