-- U2 Collective CRM Manager Portal workflow migration
-- Non-destructive: extends existing lead data and preserves current records.

BEGIN;

ALTER TABLE leads ADD COLUMN IF NOT EXISTS manager_id BIGINT REFERENCES users(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_generator_id BIGINT REFERENCES users(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS caller_id BIGINT REFERENCES users(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS current_owner_id BIGINT REFERENCES users(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS workflow_status TEXT DEFAULT 'new';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'Normal';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS manager_due_date DATE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_generation_due_date DATE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS caller_due_date DATE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS manager_assignment_notes TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_to_manager_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_to_manager_by BIGINT REFERENCES users(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_generation_instructions TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_to_lead_generator_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_to_lead_generator_by BIGINT REFERENCES users(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS caller_instructions TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_to_caller_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_to_caller_by BIGINT REFERENCES users(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS caller_notes TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS review_notes TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS caller_completed_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS caller_completed_by BIGINT REFERENCES users(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS manager_completed_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS manager_completed_by BIGINT REFERENCES users(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS interest_status TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS decision_maker_name TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS decision_maker_role TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS preferred_contact_method TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS next_follow_up_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS manager_notes TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS closure_reason TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS conversion_details TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS converted_at TIMESTAMPTZ;

UPDATE leads SET
  caller_id = COALESCE(caller_id, assigned_to),
  current_owner_id = COALESCE(current_owner_id, assigned_to),
  workflow_status = CASE
    WHEN workflow_status IS NOT NULL AND workflow_status <> 'new' THEN workflow_status
    WHEN status = 'Contracted' THEN 'converted'
    WHEN status = 'Interested' THEN 'manager_follow_up'
    WHEN status = 'Not Interested' THEN 'not_interested'
    WHEN status IN ('Called', 'No Answer') THEN 'caller_completed'
    WHEN assigned_to IS NOT NULL THEN 'assigned_to_caller'
    ELSE 'new'
  END;

CREATE TABLE IF NOT EXISTS lead_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  assigned_to BIGINT REFERENCES users(id),
  assigned_by BIGINT REFERENCES users(id),
  assigned_at TIMESTAMPTZ DEFAULT NOW(),
  active BOOLEAN DEFAULT TRUE
);

ALTER TABLE lead_assignments ADD COLUMN IF NOT EXISTS assignment_type TEXT;
ALTER TABLE lead_assignments ADD COLUMN IF NOT EXISTS assigned_from_user_id BIGINT REFERENCES users(id);
ALTER TABLE lead_assignments ADD COLUMN IF NOT EXISTS assigned_to_user_id BIGINT REFERENCES users(id);
ALTER TABLE lead_assignments ADD COLUMN IF NOT EXISTS instructions TEXT;
ALTER TABLE lead_assignments ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'Normal';
ALTER TABLE lead_assignments ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE lead_assignments ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE lead_assignments ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

CREATE TABLE IF NOT EXISTS lead_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  previous_status TEXT,
  new_status TEXT NOT NULL,
  changed_by_user_id BIGINT REFERENCES users(id),
  reason TEXT,
  metadata JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS caller_outcomes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  caller_id BIGINT NOT NULL REFERENCES users(id),
  manager_id BIGINT REFERENCES users(id),
  call_status TEXT NOT NULL,
  contact_result TEXT,
  contact_person_name TEXT,
  contact_person_role TEXT,
  phone_number_used TEXT,
  call_date DATE NOT NULL,
  call_time TIME,
  call_duration TEXT,
  interest_status TEXT,
  follow_up_required BOOLEAN DEFAULT FALSE,
  follow_up_date DATE,
  additional_contact_information TEXT,
  notes TEXT,
  completed_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lead_email_followups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  manager_id BIGINT NOT NULL REFERENCES users(id),
  email_stage TEXT NOT NULL CHECK (email_stage IN ('initial','day_3','day_7','day_14')),
  recipient_email TEXT NOT NULL,
  cc TEXT,
  subject TEXT NOT NULL,
  message_body TEXT NOT NULL,
  scheduled_for TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','scheduled','pending','sent','failed','cancelled','skipped')),
  provider_message_id TEXT,
  failure_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (lead_id, manager_id, email_stage)
);

CREATE TABLE IF NOT EXISTS lead_manager_outcomes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  manager_id BIGINT NOT NULL REFERENCES users(id),
  interest_status TEXT NOT NULL,
  decision_maker_name TEXT,
  decision_maker_role TEXT,
  preferred_contact_method TEXT,
  next_step TEXT,
  next_follow_up_at TIMESTAMPTZ,
  reason_not_interested TEXT,
  conversion_details TEXT,
  manager_notes TEXT NOT NULL,
  communication_summary TEXT NOT NULL,
  closure_reason TEXT NOT NULL,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (lead_id)
);

CREATE TABLE IF NOT EXISTS lead_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  performed_by_user_id BIGINT REFERENCES users(id),
  previous_status TEXT,
  new_status TEXT,
  metadata JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leads_manager_workflow ON leads(manager_id, workflow_status);
CREATE INDEX IF NOT EXISTS idx_leads_generator_workflow ON leads(lead_generator_id, workflow_status);
CREATE INDEX IF NOT EXISTS idx_leads_caller_workflow ON leads(caller_id, workflow_status);
CREATE INDEX IF NOT EXISTS idx_lead_assignments_history ON lead_assignments(lead_id, assigned_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_active_assignment_per_type ON lead_assignments(lead_id, assignment_type) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_lead_status_history_lead ON lead_status_history(lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_caller_outcomes_lead ON caller_outcomes(lead_id, completed_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_followups_manager ON lead_email_followups(manager_id, status, scheduled_for);
CREATE INDEX IF NOT EXISTS idx_lead_activity_timeline ON lead_activity(lead_id, created_at DESC);

ALTER TABLE lead_status_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE caller_outcomes DISABLE ROW LEVEL SECURITY;
ALTER TABLE lead_email_followups DISABLE ROW LEVEL SECURITY;
ALTER TABLE lead_manager_outcomes DISABLE ROW LEVEL SECURITY;
ALTER TABLE lead_activity DISABLE ROW LEVEL SECURITY;
GRANT ALL ON lead_status_history, caller_outcomes, lead_email_followups, lead_manager_outcomes, lead_activity TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

COMMIT;
