-- U2 Collective CRM SQLite to Supabase migration
-- Generated from local SQLite data. Run this in Supabase SQL Editor.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('CEO','Manager','Sales Representative','Marketing','Accountant','Employee')),
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  contact_person TEXT,
  email TEXT,
  phone TEXT,
  linkedin TEXT,
  country TEXT,
  state TEXT,
  city TEXT,
  source TEXT,
  service_interested TEXT,
  estimated_value NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'New Lead',
  assigned_to BIGINT REFERENCES users(id),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lead_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  file_name TEXT,
  file_path TEXT,
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS followups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  followup_date DATE,
  followup_time TEXT,
  method TEXT,
  notes TEXT,
  status TEXT DEFAULT 'Pending',
  assigned_to BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  contact_person TEXT,
  email TEXT,
  phone TEXT,
  country TEXT,
  services TEXT,
  monthly_charges NUMERIC DEFAULT 0,
  contract_start DATE,
  contract_end DATE,
  status TEXT DEFAULT 'Active',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS communications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  type TEXT,
  message TEXT,
  communication_date DATE,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  assigned_to BIGINT REFERENCES users(id),
  created_by BIGINT REFERENCES users(id),
  deadline DATE,
  priority TEXT DEFAULT 'Medium',
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  title TEXT,
  amount NUMERIC,
  status TEXT DEFAULT 'Draft',
  sent_date DATE,
  notes TEXT,
  file_path TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  amount NUMERIC,
  payment_date DATE,
  payment_method TEXT,
  status TEXT DEFAULT 'Paid',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  name TEXT NOT NULL,
  role TEXT,
  salary NUMERIC,
  phone TEXT,
  email TEXT,
  status TEXT DEFAULT 'Active',
  joining_date DATE,
  performance_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  action TEXT,
  module TEXT,
  record_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS daily_quran_ayats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  surah_number INTEGER NOT NULL,
  ayah_number INTEGER NOT NULL,
  surah_name TEXT,
  arabic_text TEXT NOT NULL,
  urdu_translation TEXT NOT NULL,
  reference TEXT,
  date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(date, surah_number, ayah_number)
);

CREATE INDEX IF NOT EXISTS idx_leads_assigned_to ON leads(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_followups_assigned_to ON followups(assigned_to);
CREATE INDEX IF NOT EXISTS idx_payments_client_id ON payments(client_id);
CREATE INDEX IF NOT EXISTS idx_daily_quran_ayats_date ON daily_quran_ayats(date);

ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lead_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS followups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS communications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS proposals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS daily_quran_ayats DISABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO anon, authenticated;

TRUNCATE TABLE "users", "clients", "leads", "lead_files", "followups", "communications", "tasks", "proposals", "payments", "employees", "activities", "daily_quran_ayats" RESTART IDENTITY CASCADE;

-- users: 1 rows
INSERT INTO "users" ("id", "name", "email", "password", "role", "status", "created_at") VALUES
  (1, 'Admin CEO', 'admin@u2collective.com', '$2a$10$Hxdd88zZVc.kAeesvusCB.HjsB8rlMnZWSYAq2DW6PRf1Qn2SnZjS', 'CEO', 'active', '2026-07-03 19:52:18');
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM "users"), 1), (SELECT COUNT(*) FROM "users") > 0);

-- clients: 1 rows
INSERT INTO "clients" ("id", "company_name", "contact_person", "email", "phone", "country", "services", "monthly_charges", "contract_start", "contract_end", "status", "notes", "created_at") VALUES
  (1, 'HealthFirst Medical', 'Dr. Alice Brown', 'alice@healthfirst.com', '+1-555-0404', 'USA', 'Medical Billing,Prior Authorization', 4500, '2024-01-01', NULL, 'Active', 'Long-term client since 2024', '2026-07-03 19:52:18');
SELECT setval(pg_get_serial_sequence('clients', 'id'), COALESCE((SELECT MAX(id) FROM "clients"), 1), (SELECT COUNT(*) FROM "clients") > 0);

-- leads: 3 rows
INSERT INTO "leads" ("id", "company_name", "contact_person", "email", "phone", "linkedin", "country", "source", "service_interested", "estimated_value", "status", "assigned_to", "notes", "created_at", "updated_at") VALUES
  (1, 'MedBill Solutions', 'John Smith', 'john@medbill.com', '+1-555-0101', '', 'USA', 'LinkedIn', 'Medical Billing', 5000, 'New Lead', 1, 'Interested in full RCM', '2026-07-03 19:52:18', '2026-07-03 19:52:18'),
  (2, 'Digital Boost Agency', 'Sarah Connor', 'sarah@digitalboost.com', '+1-555-0202', '', 'UK', 'Meta Ads', 'Digital Marketing', 3000, 'Contacted', 1, 'Needs SEO + Social Media', '2026-07-03 19:52:18', '2026-07-03 19:52:18'),
  (3, 'WebCraft Inc', 'Mike Johnson', 'mike@webcraft.com', '+1-555-0303', '', 'Canada', 'Referral', 'Web Development', 8000, 'Meeting Scheduled', 1, 'E-commerce project', '2026-07-03 19:52:18', '2026-07-03 19:52:18');
SELECT setval(pg_get_serial_sequence('leads', 'id'), COALESCE((SELECT MAX(id) FROM "leads"), 1), (SELECT COUNT(*) FROM "leads") > 0);

-- lead_files: 0 rows
-- lead_files: 0 rows
SELECT setval(pg_get_serial_sequence('lead_files', 'id'), COALESCE((SELECT MAX(id) FROM "lead_files"), 1), (SELECT COUNT(*) FROM "lead_files") > 0);

-- followups: 0 rows
-- followups: 0 rows
SELECT setval(pg_get_serial_sequence('followups', 'id'), COALESCE((SELECT MAX(id) FROM "followups"), 1), (SELECT COUNT(*) FROM "followups") > 0);

-- communications: 0 rows
-- communications: 0 rows
SELECT setval(pg_get_serial_sequence('communications', 'id'), COALESCE((SELECT MAX(id) FROM "communications"), 1), (SELECT COUNT(*) FROM "communications") > 0);

-- tasks: 0 rows
-- tasks: 0 rows
SELECT setval(pg_get_serial_sequence('tasks', 'id'), COALESCE((SELECT MAX(id) FROM "tasks"), 1), (SELECT COUNT(*) FROM "tasks") > 0);

-- proposals: 0 rows
-- proposals: 0 rows
SELECT setval(pg_get_serial_sequence('proposals', 'id'), COALESCE((SELECT MAX(id) FROM "proposals"), 1), (SELECT COUNT(*) FROM "proposals") > 0);

-- payments: 0 rows
-- payments: 0 rows
SELECT setval(pg_get_serial_sequence('payments', 'id'), COALESCE((SELECT MAX(id) FROM "payments"), 1), (SELECT COUNT(*) FROM "payments") > 0);

-- employees: 1 rows
INSERT INTO "employees" ("id", "user_id", "name", "role", "salary", "phone", "email", "status", "joining_date", "performance_notes", "created_at") VALUES
  (1, 1, 'Admin CEO', 'CEO', 15000, '+1-555-0001', 'admin@u2collective.com', 'Active', '2023-01-01', 'Founder and CEO of U2 Collective LLP', '2026-07-03 19:52:18');
SELECT setval(pg_get_serial_sequence('employees', 'id'), COALESCE((SELECT MAX(id) FROM "employees"), 1), (SELECT COUNT(*) FROM "employees") > 0);

-- activities: 0 rows
-- activities: 0 rows
SELECT setval(pg_get_serial_sequence('activities', 'id'), COALESCE((SELECT MAX(id) FROM "activities"), 1), (SELECT COUNT(*) FROM "activities") > 0);

-- daily_quran_ayats: 0 rows
-- daily_quran_ayats: 0 rows
SELECT setval(pg_get_serial_sequence('daily_quran_ayats', 'id'), COALESCE((SELECT MAX(id) FROM "daily_quran_ayats"), 1), (SELECT COUNT(*) FROM "daily_quran_ayats") > 0);

COMMIT;
