-- U2 Collective CRM non-destructive Supabase schema migration
-- Safe to rerun in Supabase SQL Editor. Existing CRM data is preserved.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('CEO','Manager','Sales Representative','Marketing','Accountant','Employee')),
  employee_type TEXT CHECK(employee_type IN ('lead_generator','caller')),
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id TEXT,
  company_name TEXT NOT NULL,
  client_clinic_name TEXT,
  clinic_website TEXT,
  clinic_linkedin TEXT,
  clinic_phone TEXT,
  clinic_email TEXT,
  practice_size TEXT,
  country TEXT,
  state TEXT,
  city TEXT,
  source TEXT,
  service_interested TEXT,
  status TEXT DEFAULT 'Not contract',
  assigned_to BIGINT REFERENCES users(id),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lead_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  file_name TEXT,
  file_path TEXT,
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS followups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  followup_date DATE,
  followup_time TEXT,
  method TEXT,
  notes TEXT,
  status TEXT DEFAULT 'Pending',
  assigned_to BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  contact_person TEXT,
  email TEXT,
  phone TEXT,
  country TEXT,
  services TEXT,
  monthly_charges NUMERIC DEFAULT 0,
  contract_start DATE,
  contract_end DATE,
  status TEXT DEFAULT 'Active',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS communications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  type TEXT,
  message TEXT,
  communication_date DATE,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  assigned_to BIGINT REFERENCES users(id),
  created_by BIGINT REFERENCES users(id),
  deadline DATE,
  priority TEXT DEFAULT 'Medium',
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  title TEXT,
  amount NUMERIC,
  status TEXT DEFAULT 'Draft',
  sent_date DATE,
  notes TEXT,
  file_path TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  amount NUMERIC,
  payment_date DATE,
  payment_method TEXT,
  status TEXT DEFAULT 'Paid',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  name TEXT NOT NULL,
  role TEXT,
  employee_type TEXT CHECK(employee_type IN ('lead_generator','caller')),
  salary NUMERIC,
  phone TEXT,
  email TEXT,
  status TEXT DEFAULT 'Active',
  joining_date DATE,
  performance_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  action TEXT,
  module TEXT,
  record_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS daily_quran_ayats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  surah_number INTEGER NOT NULL,
  ayah_number INTEGER NOT NULL,
  surah_name TEXT,
  arabic_text TEXT NOT NULL,
  urdu_translation TEXT NOT NULL,
  reference TEXT,
  date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(date, surah_number, ayah_number)
);

-- CREATE TABLE IF NOT EXISTS does not add columns to tables that already exist.
-- Keep existing Supabase installations compatible with the current application schema.
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS employee_type TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS employee_type TEXT;
ALTER TABLE IF EXISTS leads ADD COLUMN IF NOT EXISTS lead_id TEXT;
ALTER TABLE IF EXISTS leads ADD COLUMN IF NOT EXISTS client_clinic_name TEXT;
ALTER TABLE IF EXISTS leads ADD COLUMN IF NOT EXISTS clinic_website TEXT;
ALTER TABLE IF EXISTS leads ADD COLUMN IF NOT EXISTS clinic_linkedin TEXT;
ALTER TABLE IF EXISTS leads ADD COLUMN IF NOT EXISTS clinic_phone TEXT;
ALTER TABLE IF EXISTS leads ADD COLUMN IF NOT EXISTS clinic_email TEXT;
ALTER TABLE IF EXISTS leads ADD COLUMN IF NOT EXISTS practice_size TEXT;
ALTER TABLE IF EXISTS leads ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE IF EXISTS leads ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS users_employee_type_check;
ALTER TABLE IF EXISTS users ADD CONSTRAINT users_employee_type_check
  CHECK (employee_type IS NULL OR employee_type IN ('lead_generator', 'caller'));
ALTER TABLE IF EXISTS employees DROP CONSTRAINT IF EXISTS employees_employee_type_check;
ALTER TABLE IF EXISTS employees ADD CONSTRAINT employees_employee_type_check
  CHECK (employee_type IS NULL OR employee_type IN ('lead_generator', 'caller'));

CREATE INDEX IF NOT EXISTS idx_leads_assigned_to ON leads(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_lead_id ON tasks(lead_id);
CREATE INDEX IF NOT EXISTS idx_followups_assigned_to ON followups(assigned_to);
CREATE INDEX IF NOT EXISTS idx_payments_client_id ON payments(client_id);
CREATE INDEX IF NOT EXISTS idx_daily_quran_ayats_date ON daily_quran_ayats(date);

ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lead_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS followups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS communications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS proposals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS daily_quran_ayats DISABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO anon, authenticated;

-- This migration is intentionally non-destructive. Never truncate production
-- CRM data when applying schema updates.
CREATE UNIQUE INDEX IF NOT EXISTS employees_user_id_unique ON employees(user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_leads_lead_id_unique ON leads(lead_id) WHERE lead_id IS NOT NULL;

-- Bootstrap the documented administrator only when it is missing. Existing
-- accounts and changed passwords are preserved on every subsequent run.
INSERT INTO users (name, email, password, role, status)
SELECT
  'Admin CEO',
  'admin@u2collective.com',
  '$2a$10$Hxdd88zZVc.kAeesvusCB.HjsB8rlMnZWSYAq2DW6PRf1Qn2SnZjS',
  'CEO',
  'active'
WHERE NOT EXISTS (
  SELECT 1 FROM users WHERE lower(email) = 'admin@u2collective.com'
);

COMMIT;
